config/routes.rb
GogreenglobalNet::Application.routes.draw do
  
  resources :posts

  get 'landscape' => 'landscape#index'
  get 'credentials' => 'credentials#index'
  get 'porter' => 'porter#index'
  get 'janitorial' => 'janitorial#index'
  get 'contact' => 'contact#index'
  post 'contact' => 'contact#create'
  get 'faq' => 'faq#index'
  get 'about' => 'about#index'
  get 'partners' => 'partners#index'
  get 'blog' => 'blog#index'



  root 'application#index'








end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  	@page_title = "The history of our company"
  	@meta_description = "In January of 2008 Go Green Landscape & Janitorial was formed with the hopes of creating a family owned company that would provide quality commercial services to Phoenix, Arizona. The company immediately began to take off under the leadership of Drue Engels in Janitorial and Kaipo Spenser heading up the Landscaping division. The family model is one that is still followed today, and has allowed Go Green to become a company with a winning attitude that provides unrivaled customer satisfaction."
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_site_head

  def set_site_head
  	@site_title = "Go Green Landscape & Janitorial Services"
    @meta_keywords = "Landscaping, Arborist, Contractor, Irrigation, Construction, Renovations, Janitorial, Custodial, Cleaning, Woman owned, Minority, Small business, Arizona, Scottsdale, Phoenix, Chandler, Mesa, Janitorial"
  end

  def index
  	@page_title = "Overview of what we can provide"
    @meta_description = "We're a family owned and operated full service commercial landscape management company caring for properties across the valley. We pride ourselves in maintaining all our properties to meet and exceed industry standards and always outperforming customer expectations. At Go Green customer satisfaction is our number one goal and the professional care we take with our properties allows us to achieve this."
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

	def index
		@posts = Post.paginate(:page => params[:page], :per_page => 3).order('id DESC')

		@latest = Post.order('id DESC').limit(10)
	end

end

app/controllers/contact_controller.rb
include ERB::Util

class ContactController < ApplicationController
  def index
  	@page_title = "How to contact us in Phoenix, AZ"
  	@meta_description = "Where you can find us. Business Office 2331 East Alameda Drive Tempe, AZ 85254 Phone: 602-910-4220 Fax: 866-666-1364 Mailing Address 7119 East Shea Blvd Ste. 109 PMB 227 Tempe, AZ 85254"
  end

  # POST /
  def create
  	UserMailer.quote_email(params).deliver

  	params['name'] = html_escape(params['name'])
  	params['email'] = html_escape(params['email'])
  	params['phone'] = html_escape(params['phone'])
  	params['request'] = html_escape(params['request'])

  	render :json => { json: params, status: :success, status_code: "200" }
  end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def index
  	@page_title = "Frequently asked questions"
  	@meta_description = "Why Go Green? We're a company built on quality, integrity, and customer service. In order to properly landscape a property, you must be able to handle all aspects of that property's needs. Go Green's combination of great leadership and training allows us to provide for every aspect of your landscaping needs. Attention to detail will always set us apart from our competition"
  end
end

app/controllers/janitorial_controller.rb
class JanitorialController < ApplicationController
  def index
  	@page_title = "Janitorial help we provide in Phoenix, AZ"
  	@meta_description = "Go Green believes in following a model that provides the highest quality janitorial services, and since most janitorial services are provided after business hours, you can remain confident that we only hire and keep the most honest and trustworthy employees to service your facilities."
  end
end

app/controllers/landscape_controller.rb
class LandscapeController < ApplicationController
  def index
  	@page_title = "Landscaping help we provide in Phoenix, AZ"
  	@meta_description = "Here at Go Green, we recognize that each property is going to be unique, with different objectives and challenges that need to be met. Landscape maintenance requires a lot of effort and hard work in order to achieve the goals set forth by the customer, and our teams unwavering attention to detail allows us to meet and exceed these goal"
  end
end

app/controllers/porter_controller.rb
class PorterController < ApplicationController
  def index
  	@page_title = "Porter help we provide in Phoenix, AZ"
  	@meta_descriptiom = "During normal business hours it is important to keep your facility clean and neat. Go Green offers day porter services to assist in a variety of tasks. Daily / Weekly porter service schedules"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @latest = Post.limit(3).order('id DESC')
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :title, :body)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_image(image_path, target_link, img_options={}, link_options={})
  		link_to(image_tag(image_path, img_options), target_link, link_options)
	end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/janitorial_helper.rb
module JanitorialHelper
end

app/helpers/landscape_helper.rb
module LandscapeHelper
end

app/helpers/porter_helper.rb
module PorterHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/about/index.html.erb
<div id="content-body-about" class="content row">
	<div class="col-lg-12">
		<h1 class="boxed-header">Our History</h1>
		<%= image_tag("logo-gogreen.svg", alt: "Go Green logo", id: "logo-gogreen", class: "img-responsive") %>
		<p><brand>Go Green Landscape &amp; Janitorial</brand> is a family owned and operated company. <brand>Go Green</brand> is certified as a business, owned and controlled by a woman, through the NWBOC. <brand>Go Green's</brand> management team has been providing quality services to the Valley for over 35 years for large commercial entities, including malls, high rises, hospitals, manufacturing centers, office buildings, and retail centers. The “family” model is one that is still followed today and has allowed <brand>Go Green</brand> to become a company with a winning attitude that provides unrivaled customer satisfaction. Communication is a huge part of what we believe leads to quality relationships. With <brand>Go Green</brand> you will always remain informed and satisfied with the maintenance services we provide. Our management team relies on our commitment to quality and our vast experience in the janitorial field. We have our own 24/7 interactive Help Desk that is an integral part of our quality control and issue identification system.</p>
		<p>Cathleen Engels is president and managing partner of <brand>Go Green Landscape &amp; Janitorial</brand>.  Cathy grew up in Tucson and graduated from the University of Arizona. Having owned and operated many family businesses, she has over 30 years of experience in the areas of real estate development and investment, luxury home property management, and interior design. Under Cathleen’s management <brand>Go Green</brand> has received certification by the National Women Business Owners Corporation (NWBOC), as a business owned and controlled by a woman. She believes in providing high quality janitorial services backed by unsurpassed customer service and technology. Cathleen handles the financial management and works closely with the management teams to ensure the quality of the services we provide are maintained </p>
		<p>Drue Engels is a managing partner of Go Green and has over 35 years of experience in the industry. He grew up in Phoenix and attended Arizona State University. Drue along with his father Chuck Engels started a janitorial service company in Phoenix, Arizona in 1978. One of their first clients was Litton Industries, which Go Green still services today. They expanded service and opened offices in Albuquerque, New Mexico; Pasadena, California; and Tucson, Arizona. In 1998, they sold their company to a large, publicly held janitorial company. Under the guidance of Drue the company grew to approximately 1,500 employees and generated revenue of just under $40 million per year. Drue oversees the daily operation and coordination of our services, including customer relations.</p>
	</div>
</div>

app/views/application/index.html.erb
<div class="content row">
	<div class="col-lg-12">
		<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
			<!-- Indicators -->
			<ol class="carousel-indicators">
				<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
				<li data-target="#carousel-example-generic" data-slide-to="1"></li>
				<li data-target="#carousel-example-generic" data-slide-to="2"></li>
				<li data-target="#carousel-example-generic" data-slide-to="2"></li>
			</ol>

			<!-- Wrapper for slides -->
			<div class="carousel-inner">
				<div class="item active">
					<a href="assets/home-1-original.jpg" title="Go Green" data-gallery>
						<%= image_tag("home-1.jpg", alt: "Go Green Landscape & Janitorial") %>
					</a>
				      <div class="carousel-caption">
				        <p>Go Green Landscape &amp; Janitorial</p>
				    </div>
				</div>
				<div class="item">
					<a href="assets/home-2-original.jpg" title="Go Green" data-gallery>
						<%= image_tag("home-2.jpg", alt: "Go Green Landscape services") %>
					</a>
				      <div class="carousel-caption">
				        <p><%= link_to "Go Green Landscape services", landscape_path, class: "underline" %></p>
				    </div>
				</div>
				<div class="item">
					<a href="assets/home-3-original.jpg" title="Go Green" data-gallery>
						<%= image_tag("home-3.jpg", alt: "Go Green Janitorial services") %>
					</a>
				      <div class="carousel-caption">
				        <p><%= link_to "Go Green Janitorial services", janitorial_path, class: "underline" %></p>
				    </div>
				</div>	
				<div class="item">
					<a href="assets/home-4-original.jpg" title="Go Green" data-gallery>
						<%= image_tag("home-4.jpg", alt: "Go Green Porter services") %>
					</a>
				      <div class="carousel-caption">
				        <p><%= link_to "Go Green Porter services", porter_path, class: "underline" %></p>
				    </div>
				</div>									    				    
			</div>

			<!-- Controls -->
			<a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
				<i class="fa glyphicon-chevron-left fa-chevron-left"></i>
			</a>
			<a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
				<i class="fa glyphicon-chevron-right fa-chevron-right"></i>
			</a>
		</div>	
	</div>
</div>
<div class="content row">
	<div class="col-lg-6">
		<div id="intro">
			<p><brand>Go Green</brand> is a full service commercial landscape and janitorial service provider for the greater Phoenix metro area. <brand>Go Green</brand> is a nationally certified woman owned business, by the NWBOC.</p>
		</div>
	</div>
	<div class="col-lg-6">
		<div id="sub-intro">
			<p>At <brand>Go Green</brand> we provide industry-leading services, with customer satisfaction as our number one goal. Our skilled professionals provide landscape and janitorial services unmatched by other companies. See how the <brand>Go Green</brand> team can work for you.</p>
		</div>	
	</div>
</div>
<div class="content row">
	<div class="col-lg-12 home-offer">
		<h1 class="boxed-header">Services offered</h1>
		<div class="row">
			<div class="col-md-4">
				<h2>Janitorial</h2>
				<p>Our dedicated team of janitorial professionals will provide industry leading cleaning for your facility. Our services are based on industry standards, and we pride ourselves on adapting based best care methods. Our janitorial services include <brand>Green Cleaning</brand> methods, as well as access to building LEED certification and sustainability programs.</p>
				<p><%= link_to "View our janitorial services", janitorial_path, class: "underline" %></p>
			</div>
			<div class="col-md-4">
				<h2>Landscaping</h2>
				<p>Creating and maintaining a beautiful landscape takes knowledge, care, and dedication. We service all types of commercial properties and HOA communities. A full service landscape company, we can provide for all the needs of your property or community.</p>
				<p><%= link_to "See how we can help", landscape_path, class: "underline" %></p>
			</div>
			<div class="col-md-4">
				<h2>Porter</h2>
				<p>We can provide porter services to ensure your property stays looking neat and clean. Maintaining your property with porter services from <brand>Go Green</brand> will provide you services based on your specific needs.</p>
				<p><%= link_to "View our porter services", porter_path, class: "underline" %></p>
			</div>
		</div>
	</div>
</div>
<div class="content row">
	<div class="col-lg-12">
		<div class="row">
			<div class="col-md-8">
				<%= image_tag("contact-group.jpg", class: "img-responsive") %>
			</div>
			<div class="col-md-4">
				<p>We're a family owned, and operated, business with our office located in Scottsdale, AZ.</p>
				<p>Get to know us and we'll show you why our personable service can't be matched anywhere else.</p>
				<p><%= link_to "Meet our team", contact_path, class: "underline" %></p>
			</div>
		</div>
	</div>
</div>
<div class="content row">
	<div class="col-lg-12" id="quality-service">
		<h1 class="boxed-header">Qualifications</h1>
		<div class="row">
			<div class="col-md-12">
				<div class="row">
					<div class="col-md-4">
						<%= link_to image_tag("logo-raz.png", class: "img-responsive", alt: "Ranking Arizona"), "http://azbigmedia.com/ranking-arizona", "target" => "_blank" %>
						</div>
					<div class="col-md-4">
						<%= link_to image_tag("logo-roc.png", class: "img-responsive", alt: "Arizona Licensed Contractor"), "http://www.azroc.gov/", "target" => "_blank" %>
					</div>
					<div class="col-md-4">
						<%= link_to image_tag("logo-nwboc.png", class: "img-responsive", alt: "Arizona Licensed Contractor"), "http://www.nwboc.org/", "target" => "_blank" %>
					</div>					
				</div>
				<div class="row">
					<div class="col-md-4">
						<p>Voted a "Top 10" Landscape and Janitorial Service Provider</p>
					</div>
					<div class="col-md-4">
						<p><brand>Go Green</brand> is a registered contractor. Licensed, bonded, and insured.</p>
					</div>	
					<div class="col-md-4">
						<p><brand>Go Green</brand> is a woman owned business.</p>
					</div>										
				</div>
			</div>
		</div>
	</div>
</div>

app/views/blog/index.html.erb
<div id="blog" class="content row">
	<div id="latest-posts" class="col-lg-3 col-lg-push-9">
		<h3>Latest posts:</h3>
		<ul>
			<% @latest.each do |l| %>
				<li>
					<%= link_to l.title, l, :class => 'underline' %><span class="post-meta">Posted by <%= l.user_id %> on 09/18/2014</span>
				</li>
			<% end %>
		</ul>
	</div>
	<div class="col-lg-9 col-lg-pull-3">
		<% @posts.each do |post| %>
			<h2><%= post.title %></h2>
			<h4>Published on September 18, 2014 by <a href="#"><%= post.user_id %></a></h4>
			<%= raw post.body %>
			<p><%= link_to 'Continue reading', post, :class => 'underline' %></p>
		<% end %>
	</div>
</div>
<div class="content row">
	<div class="col-lg-12">
		<%= will_paginate @posts %>
	</div>
</div>

app/views/contact/index.html.erb
<div class="content row">
	<div class="col-lg-12">
		<div class="content-body content-body-contact">
			<div class="row">
				<div class="col-md-12">
					<h1 class="boxed-header">Contact us</h1>
				</div>
				<div class="col-md-4">
					<div>
						<div class="panel-heading"><h2>Business Address</h2></div>
						<div class="panel-body">
							<h4><i class="fa fa-building-o"></i> 10632 N. Scottsdale Rd #227</h4>
							<h4>Scottsdale, AZ 85254</h4>
							<h4><i class="fa fa-phone fa-fw"></i> (602) 910-4220</h4>
							<h4>Fax: (866) 666-1364</h4>							
						</div>
					</div>					
				</div>
				<div class="col-md-8">
					<%= image_tag("contact-group.jpg", class: "img-responsive") %>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<h1 class="boxed-header">Map us</h1>
				</div>
				<div class="col-md-12">
					<iframe width="100%" height="200" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?q=10632+N.+Scottsdale+Rd+%23227+Scottsdale,+AZ+85254&amp;ie=UTF8&amp;hq=&amp;hnear=10632+N+Scottsdale+Rd+%23227,+Scottsdale,+Arizona+85254&amp;gl=us&amp;ll=33.582824,-111.925836&amp;spn=0.016035,0.033023&amp;t=m&amp;z=14&amp;output=embed"></iframe>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<h1 class="boxed-header">Get to know us</h1>
				</div>
				<div class="col-md-3 bio">
					<div>
						<div class="thumbnail">
							<%= image_tag("contact-drue.png", class: "img-responsive avatar") %>
						</div>
						<div class="panel-heading contact-name"><h2>Drue<br />Engels</h2></div>
						<div class="panel-body">
							<h4>Managing Partner</h4>
							<h6>Janitorial Operations</h6>
							<h6><i class="fa fa-envelope fa-fw"></i> drue@gogreenglobal.net</h6>
							<div id="accordion">
								<div>
									<h4 class="boxed-header">
										<a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
											Bio
										</a>
									</h4>
									<div id="collapseOne" class="panel-collapse collapse">
										<div class="panel-body">
											<p>Drue Engels oversees business development and participates in the overall management of Go Green.  With over 35 years in the industry, Drue lends his knowledge and expertise to contribute to “The Green Team.”</p>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>		
				</div>
				<div class="col-md-3 bio">
					<div>
						<div class="thumbnail">
							<%= image_tag("contact-cathy.png", class: "img-responsive avatar") %>
						</div>
						<div class="panel-heading contact-name"><h2>Cathy<br />Engels</h2></div>
						<div class="panel-body">
							<h4>President</h4>
							<h6>Accounting</h6>
							<h6><i class="fa fa-envelope fa-fw"></i> cathy@gogreenglobal.net</h6>
							<div id="accordion">
								<div>
									<h4 class="boxed-header">
										<a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
											Bio
										</a>
									</h4>
									<div id="collapseTwo" class="panel-collapse collapse">
										<div class="panel-body">
											<p>Cathy is responsible for Go Green’s designation as a nationally certified woman owned business.  She runs the company's finances, and is a steady hand in the future of the company.</p>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>	
				</div>
				<div class="col-md-3 bio">
					<div>
						<div class="thumbnail">
							<%= image_tag("contact-kaipo.png", class: "img-responsive avatar") %>
						</div>
						<div class="panel-heading contact-name"><h2>Kaipo<br />Spencer</h2></div>
						<div class="panel-body">
							<h4>Director of Operations</h4>
							<h6>Landscape Operations</h6>
							<h6><i class="fa fa-envelope fa-fw"></i> kaipo@gogreenglobal.net</h6>
							<div id="accordion">
								<div>
									<h4 class="boxed-header">
										<a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
											Bio
										</a>
									</h4>
									<div id="collapseThree" class="panel-collapse collapse">
										<div class="panel-body">
											<p>Kaipo oversees the day-to-day operations of Go Green’s landscape division. With many years in the industry, his knowledge and professionalism help set apart Go Green from other companies.</p>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>	
				</div>
				<div class="col-md-3 bio">
					<div>
						<div class="thumbnail">
							<%= image_tag("contact-cody.png", class: "img-responsive avatar") %>
						</div>
						<div class="panel-heading contact-name"><h2>Cody<br />McCloskey</h2></div>
						<div class="panel-body">
							<h4>Director of Operations</h4>
							<h6>Janitorial Operations</h6>	
							<h6><i class="fa fa-envelope fa-fw"></i> cody@gogreenglobal.net</h6>
							<div id="accordion">
								<div>
									<h4 class="boxed-header">
										<a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
											Bio
										</a>
									</h4>
									<div id="collapseFour" class="panel-collapse collapse">
										<div class="panel-body">
											<p>Cody oversees the day-to-day operations of Go Green’s janitorial division, and aids in the management of the landscape divisions HOA portfolio. He is responsible for implementing and monitoring the company’s business development for both divisions.</p>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>	
				</div>
			</div>
		</div>
	</div>
</div>

app/views/faq/index.html.erb
<div class="content row">
	<div class="col-lg-12">
		<h1 class="boxed-header">Frequently Asked Questions</h1>
		<%= image_tag("faq-large.jpg", alt: "Frequently asked questions", class: "img-responsive") %>
		<dl>
			<dt><h3>Why Go Green?</h3></dt>
			<dd class="list-group-item"><p>We're a company built on quality, integrity, and customer service. In order to properly landscape a property, you must be able to handle all aspects of that property's needs. <brand>Go Green's</brand> combination of great leadership and training allows us to provide for every aspect of your landscaping needs. Attention to detail will always set us apart from our competition.</p></dd>
			<dt><h3>How can I conserve water and save money?</h3></dt>
			<dd class="list-group-item"><p>Water conservation is an important part of any successful landscape plan. Our certified irrigation technician will analyze all of the watering needs for the landscaping on your property. Proper watering will always be based on plant type and season. Most importantly, knowing how much water plants need to stay healthy, without over watering, will help you save money.</p></dd>
			<dt><h3>What is the difference between natural and manicured pruning?</h3></dt>
			<dd class="list-group-item"><p>If you would like to have a natural look for your property then pruning will be done on an as needed basis, this includes cutbacks. This look will consist of allowing a plant to keep its natural form, and only be pruned to keep it from becoming an obstruction. A manicured look will keep the plant trimmed at all times in a neat, compact shape. These two pruning methods are both acceptable, and are implemented due to customers preference.</p></dd>
			<dt><h3>Why would I need to cut certain plants back?</h3></dt>
			<dd class="list-group-item"><p>During the winter certain plants may become damaged by a frost. When this occurs the plant material that was affected must be removed in order to allow the plant to produce new growth. Generally these cutbacks will be done in early March, right before the growing season begins.</p></dd>
			<dt><h3>Why do I need to overseed my grass each year?</h3></dt>
			<dd class="list-group-item"><p>The most common species of grass around the valley happen to be Bermuda and Tiffway grasses. Both of these species are warm weather grasses that do very well about 7 months out of the year. After these 7 months, when it starts to get cold, these grasses will enter a dormant period, and start to brown out. At this point scalping will take place where your grass is cut to almost bare dirt, and then a winter rye seed will be applied. This practice will ensure you have a beautiful green lawn throughout the year.</p></dd>
			<dt><h3>When and why do I need to fertilize on my property?</h3></dt>
			<dd class="list-group-item"><p>Fertilization is essential in order to keep grass, plants, and trees healthy on your property. Fertilization of grass will be done a minimum of 4 times throughout the year in order to keep lawn well fed and green. Plants and trees should be fertilized on an as needed basis. Our landscaping team is trained to spot deficiencies and report them in order to formulate proper fertilization plans.</p></dd>
		</dl>
	</div>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, :class => "tinymce", :rows => 10, :cols => 120 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div id="posts" class="content row">
  <div class="col-lg-12">

<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
	</div>
</div>

app/views/posts/index.html.erb
<div id="posts" class="content row">
  <div class="col-lg-12">
    <h1>Listing posts</h1>

    <table>
      <thead>
        <tr>
          <th>User id</th>
          <th>Title</th>
          <th>Body</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= post.user_id %></td>
            <td><%= post.title %></td>
            <td><%= post.body %></td>
            <td><%= link_to 'Show', post %></td>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
            <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Post', new_post_path %>
  </div>
</div>

app/views/posts/new.html.erb
<div id="posts" class="content row">
  <div class="col-lg-12">

	<h1>New post</h1>

	<%= render 'form' %>

	<%= link_to 'Back', posts_path %>
	
	</div>
</div>

app/views/posts/show.html.erb
<div id="posts" class="content row">
	<div id="latest-posts" class="col-lg-3 col-lg-push-9">
		<h3>Latest posts:</h3>
		<ul>
			<% @latest.each do |l| %>
				<li>
					<%= link_to l.title, l, :class => 'underline' %><span class="post-meta">Posted by <%= l.user_id %> on 09/18/2014</span>
				</li>
			<% end %>
		</ul>
	</div>
	<div class="col-lg-9 col-lg-pull-3">
		<h2><%= @post.title %></h2>
		<h4>Published on September 18, 2014 by <a href="#"><%= @post.user_id %></a></h4>
		<%= raw @post.body %>
		<%= link_to 'Back', blog_path, :class => 'underline' %>
	</div>
</div>