config/routes.rb
GogreenglobalNet::Application.routes.draw do
  
  resources :posts

  get 'landscape' => 'landscape#index'
  get 'credentials' => 'credentials#index'
  get 'porter' => 'porter#index'
  get 'janitorial' => 'janitorial#index'
  get 'contact' => 'contact#index'
  post 'contact' => 'contact#create'
  get 'faq' => 'faq#index'
  get 'about' => 'about#index'
  get 'partners' => 'partners#index'
  get 'blog' => 'blog#index'



  root 'application#index'








end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  	@page_title = "The history of our company"
  	@meta_description = "In January of 2008 Go Green Landscape & Janitorial was formed with the hopes of creating a family owned company that would provide quality commercial services to Phoenix, Arizona. The company immediately began to take off under the leadership of Drue Engels in Janitorial and Kaipo Spenser heading up the Landscaping division. The family model is one that is still followed today, and has allowed Go Green to become a company with a winning attitude that provides unrivaled customer satisfaction."
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

	def index
		@posts = Post.paginate(:page => params[:page], :per_page => 3).order('id DESC')

		@latest = Post.order('id DESC').limit(10)
	end

end

app/controllers/contact_controller.rb
include ERB::Util

class ContactController < ApplicationController
  def index
  	@page_title = "How to contact us in Phoenix, AZ"
  	@meta_description = "Where you can find us. Business Office 2331 East Alameda Drive Tempe, AZ 85254 Phone: 602-910-4220 Fax: 866-666-1364 Mailing Address 7119 East Shea Blvd Ste. 109 PMB 227 Tempe, AZ 85254"
  end

  # POST /
  def create
  	UserMailer.quote_email(params).deliver

  	params['name'] = html_escape(params['name'])
  	params['email'] = html_escape(params['email'])
  	params['phone'] = html_escape(params['phone'])
  	params['request'] = html_escape(params['request'])

  	render :json => { json: params, status: :success, status_code: "200" }
  end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def index
  	@page_title = "Frequently asked questions"
  	@meta_description = "Why Go Green? We're a company built on quality, integrity, and customer service. In order to properly landscape a property, you must be able to handle all aspects of that property's needs. Go Green's combination of great leadership and training allows us to provide for every aspect of your landscaping needs. Attention to detail will always set us apart from our competition"
  end
end

app/controllers/janitorial_controller.rb
class JanitorialController < ApplicationController
  def index
  	@page_title = "Janitorial help we provide in Phoenix, AZ"
  	@meta_description = "Go Green believes in following a model that provides the highest quality janitorial services, and since most janitorial services are provided after business hours, you can remain confident that we only hire and keep the most honest and trustworthy employees to service your facilities."
  end
end

app/controllers/landscape_controller.rb
class LandscapeController < ApplicationController
  def index
  	@page_title = "Landscaping help we provide in Phoenix, AZ"
  	@meta_description = "Here at Go Green, we recognize that each property is going to be unique, with different objectives and challenges that need to be met. Landscape maintenance requires a lot of effort and hard work in order to achieve the goals set forth by the customer, and our teams unwavering attention to detail allows us to meet and exceed these goal"
  end
end

app/controllers/porter_controller.rb
class PorterController < ApplicationController
  def index
  	@page_title = "Porter help we provide in Phoenix, AZ"
  	@meta_descriptiom = "During normal business hours it is important to keep your facility clean and neat. Go Green offers day porter services to assist in a variety of tasks. Daily / Weekly porter service schedules"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @latest = Post.limit(3).order('id DESC')
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :title, :body)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_image(image_path, target_link, img_options={}, link_options={})
  		link_to(image_tag(image_path, img_options), target_link, link_options)
	end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/janitorial_helper.rb
module JanitorialHelper
end

app/helpers/landscape_helper.rb
module LandscapeHelper
end

app/helpers/porter_helper.rb
module PorterHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title><%= @site_title %> | <%= @page_title %></title>
	<meta name="description" content="<%= @meta_description %>" />
	<meta name="keywords" content="<%= @meta_keywords %>" />
	<meta property="og:title" content="<%= @site_title %> | <%= @page_title %>" />
	<meta property="og:description" content="<%= @meta_description %>" />
	<meta property="og:url" content="<%= request.original_url %>" />
	<link rel="canonical" href="<%= request.original_url %>" />
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
	<link href='http://fonts.googleapis.com/css?family=Glegoo' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css'>
</head>
<body>
	<!-- Modal -->
	<div class="modal fade" id="quote-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title" id="myModalLabel">Quote Request Submission</h4>
				</div>
				<div class="modal-body">
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>
			</div>
		</div>
	</div>
	<!-- End Modal -->
	<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
	<div id="blueimp-gallery" class="blueimp-gallery" data-use-bootstrap-modal="false">
	    <!-- The container for the modal slides -->
	    <div class="slides"></div>
	    <!-- Controls for the borderless lightbox -->
	    <h3 class="title"></h3>
	    <a class="prev">‹</a>
	    <a class="next">›</a>
	    <a class="close">×</a>
	    <a class="play-pause"></a>
	    <ol class="indicator"></ol>
	    <!-- The modal dialog, which will be used to wrap the lightbox content -->
	    <div class="modal fade">
	        <div class="modal-dialog">
	            <div class="modal-content">
	                <div class="modal-header">
	                    <button type="button" class="close" aria-hidden="true">&times;</button>
	                    <h4 class="modal-title"></h4>
	                </div>
	                <div class="modal-body next"></div>
	                <div class="modal-footer">
	                    <button type="button" class="btn btn-default pull-left prev">
	                        <i class="glyphicon glyphicon-chevron-left"></i>
	                        Previous
	                    </button>
	                    <button type="button" class="btn btn-primary next">
	                        Next
	                        <i class="glyphicon glyphicon-chevron-right"></i>
	                    </button>
	                </div>
	            </div>
	        </div>
	    </div>
	</div>
	<!-- End The Bootstrap Image Gallery lightbox -->
	<div id="site-container">
		<div id="header-container">
			<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
				<div class="container">
					<!-- Brand and toggle get grouped for better mobile display -->
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<%= active_link_to raw('<i class="fa fa-home"></i>'), root_path, :class => "navbar-brand", :active => :exclusive %>
					</div>

					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<ul class="nav navbar-nav">
							<%= active_link_to "Janitorial", janitorial_path, :wrap_tag => :li %>
							<%= active_link_to "Landscape", landscape_path, :wrap_tag => :li %>
							<%= active_link_to "Porter", porter_path, :wrap_tag => :li %>
						</ul>
						<ul class="nav navbar-nav navbar-right">
							<%= active_link_to "History", about_path, :wrap_tag => :li %>
							<%= active_link_to "FAQ", faq_path, :wrap_tag => :li %>
							<%= active_link_to "Contact", contact_path, :wrap_tag => :li %>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">Help Desk <b class="caret"></b></a>
								<ul class="dropdown-menu">			            
									<li><a href="http://gogreen.novosolutions.net/login.asp?stay=1&goUrl=/Default.asp">Client login</a></li>			            
									<li><a href="http://gogreen.novosolutions.net/admin/login.asp?stay=1&goUrl=/admin/Default.asp">Go Green login</a></li>
								</ul>
							</li>
						</ul>
					</div><!-- /.navbar-collapse -->
				</div><!-- /.container-fluid -->
			</nav>		
			<div class="container">
				<div class="header">
					<%= link_to_image('gogreen-mainlogo.png', '/', { :class => 'img-responsive', :alt => 'Go Green Landscape & Janitorial logo' }) %>
				</div>
			</div>
		</div>
		<div id="main-container" class="container">
			<%= yield %>
			<div id="secondary-nav" class="row">
				<%= form_tag('/contact', remote: true, id: "quote-form") do |f| %>
				<div class="quote col-md-12">
					<div class="row">
						<div class="col-md-12">	
							<h2>Send us a request</h2>
						</div>
					</div>
					<div class="row">
						<div class="col-md-5">													
							<div class="form-group">
								<label for="name">Name:</label>
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
									<%= text_field_tag 'name', '', class: "form-control nav-input", placeholder: 'Enter full name' %>
								</div>						
							</div>
							<div class="form-group">
								<label for="email">Email address:</label>
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-envelope fa-fw"></i></span>
									<%= email_field_tag 'email', '', class: "form-control nav-input", placeholder: 'Enter email' %>
								</div>
							</div>
							<div class="form-group">
								<label for="phone">Phone number:</label>
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-phone fa-fw"></i></span>
									<%= telephone_field_tag 'phone', '', class: "form-control nav-input", placeholder: 'Enter phone number' %>
								</div>
							</div>						
						</div>
						<div class="col-md-7">
							<div class="form-group">
								<label for="request">Description of request:</label>
								<!-- <textarea class="form-control nav-input" id="quote-desc" placeholder="Enter description" rows="4"></textarea> -->	
								<%= text_area_tag 'request', nil, class: 'form-control nav-input', placeholder: "Enter description", rows: "4" %>
							</div>											 														
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<%= submit_tag "Submit", class: 'btn btn-default' %>
						</div>
					</div>
				</div>
				<% end %>					
			</div>
			<div class="row affiliates">
				<div class="col-md-2">
					<%= link_to image_tag("logo-sacc.svg", alt: "Building Owners and Managers Association International logo"), "https://scottsdalechamber.com/", "target" => "_blank" %>
				</div>
				<div class="col-md-2">
					<%= link_to image_tag("logo-aacm.png", alt: "Building Owners and Managers Association International logo"), "http://aacm.com/", "target" => "_blank" %>
				</div>
				<div class="col-md-2">
					<%= link_to image_tag("logo-usgbc.png", alt: "Building Owners and Managers Association International logo"), "http://www.usgbc.org/", "target" => "_blank" %>
				</div>
				<div class="col-md-2">
					<%= link_to image_tag("logo-azroc.svg", alt: "Building Owners and Managers Association International logo"), "http://www.azroc.gov/", "target" => "_blank" %>
				</div>
				<div class="col-md-2">
					<%= link_to image_tag("logo-shc.svg", alt: "Building Owners and Managers Association International logo"), "http://www.shc.org/", "target" => "_blank" %>
				</div>
				<div class="col-md-2">
					<%= link_to image_tag("logo-cia.svg", alt: "Building Owners and Managers Association International logo"), "#", "target" => "_blank" %>
				</div>
			</div>
			<div class="row affiliates">
				<div class="col-md-2 col-md-offset-1">
					<%= link_to image_tag("logo-alca.png", alt: "Building Owners and Managers Association International logo"), "http://www.azlca.com/", "target" => "_blank" %>
				</div>
				<div class="col-md-2 col-md-offset-2">
					<%= link_to image_tag("logo-ifma.png", alt: "International Facility Management Association logo"), "http://www.ifma.org/", "target" => "_blank" %>	
				</div>
				<div class="col-md-2 col-md-offset-2">
					<%= link_to image_tag("logo-raz.svg", alt: "U.S. Green Building Council logo"), "http://azbigmedia.com/ranking-arizona", "target" => "_blank" %>
				</div>
			</div>		
		</div>
	</div>
	<footer>
		<div id="footer-content">
			<div class="container">
				<div class="footer clearfix">
					<h2>Go Green Landscape &amp; Janitorial</h2>
					<h4>10632 N. Scottsdale Rd #227</h4>
					<h4>Scottsdale, AZ 85254</h4>		
<!-- 					<a target="_blank" href="http://facebook.com"><i class="fa fa-facebook-square" title="Visit us on Facebook"></i></a>
					<a target="_blank" href="http://twitter.com/gogreenservice"><i class="fa fa-twitter-square" title="Follow us on Twitter"></i></a>
					<a target="_blank" href="http://instagram.com"><i class="fa fa-instagram" title="See us on Instagram"></i></a> -->
				</div>	
			</div>
		</div>
	</footer>	
</body>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53224513-1', 'auto');
  ga('send', 'pageview');
</script>
</html>